Repository ssg8288/Surviellance-Bomb-Diffusion-Robot, pull requests merged in 2021-01, with the labels that each got.

#18 Update Documentation.md
  Robotic ARM Tx and Rx Arduino Code/Documentation.md
Labels: DWOC, DWOC2020, Level-2, help wanted

#17 contributors button error resolved
  README.md
Labels: DWOC, DWOC2020, Level-1

#19 Updated Documentation
  Robotic ARM Tx and Rx Arduino Code/Documentation.md
Labels: DWOC, DWOC2020, Level-2, help wanted

#20 Robotic_arm_code
  Robotic ARM Tx and Rx Arduino Code/Untitled Diagram.drawio
  Robotic ARM Tx and Rx Arduino Code/robotic_arm_code
Labels: DWOC, DWOC2020, Level-5, help wanted

#24 Added the updated Block Diagram of Crawler circuit
  README.md
  Robotic ARM Tx and Rx Arduino Code/Block diagram_Surviellance.png
Labels: DWOC, DWOC2020, Level-1, bug

#26 Code and documentation updated
  DOCUMENTATION FOR GPS OR GSM VEHICLE TRACKING FOR ARDUINO/Documentation.md
  DOCUMENTATION FOR GPS OR GSM VEHICLE TRACKING FOR ARDUINO/Screenshot 2021-01-08 111811.png
  DOCUMENTATION FOR GPS OR GSM VEHICLE TRACKING FOR ARDUINO/code.ino
  DOCUMENTATION FOR GPS OR GSM VEHICLE TRACKING FOR ARDUINO/gps-vehicle-tracking-system-circuit-diagram_0.png
Labels: DWOC, DWOC2020, Level-2, Level-5, help wanted

#27 documentation updated
  DOCUMENTATION FOR GPS OR GSM VEHICLE TRACKING FOR ARDUINO/Documentation.md
Labels: DWOC, DWOC2020, Level-2, help wanted

#28 PR template
  .github/pull_request_template.md
Labels: DWOC, DWOC2020, Level-1, help wanted

#31 Solved issue #30 By solving the bug and updating the diagram.
  Crawler/Block diagram_Surviellance.png
  README.md
Labels: DWOC, DWOC2020, Level-3, bug, help wanted

#34 Documentation for the Internet based control for the Crawler
  Internet based control/Documentation.md
  Internet based control/Movement_ss_Crawler.png
  Internet based control/ajaxform.js
  Internet based control/arduino_code.ino
  Internet based control/down.png
  Internet based control/index.html
  Internet based control/jquery.js
  Internet based control/left.png
  Internet based control/right.png
  Internet based control/up.png
Labels: DWOC, DWOC2020, Level-5, help wanted
